import type { Metadata } from "next";
import "./globals.css";
import LeftBar from "@/components/LeftBar";
import RightBar from "@/components/RightBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-screen-md lg:max-w-screen-lg flex justify-between mx-auto">
          <div className="">
            <LeftBar />
          </div>
          <div className="">{children}</div>
          <div className="">
            <RightBar />
          </div>
        </div>
      </body>
    </html>
  );
}
